[package]
name = "MinecraftDioramaRaytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
minifb = "0.27.0"
nalgebra = "0.33.0"
nalgebra-glm = "0.19.0"
once_cell = "1.19.0"
rand = "0.8.5"
rayon = "1.10.0"
rodio = "0.19.0"
winit = "0.30.5"
